[tool.poetry]
name = "page-analyzer"
version = "0.1.0"
description = ""
authors = ["Barzabek <kochenko1995@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
